version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - tempo
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/config/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config/config.yml:ro
      - loki-data:/loki
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: -config.file=/etc/tempo/config.yml
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # OTLP/HTTP
    volumes:
      - ./tempo/config.yml:/etc/tempo/config.yml:ro
      - tempo-data:/var/tempo
    networks:
      - observability

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - promtail-positions:/tmp
    depends_on:
      - loki
    networks:
      - observability

  app:
    build: ./app
    container_name: flask-app
    environment:
      - LOG_LEVEL=INFO
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4318/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp
    ports:
      - "8000:8000"
    depends_on:
      - tempo
    labels:
      - "promtail=true"   # allow promtail to scrape logs
    networks:
      - observability

networks:
  observability:
    driver: bridge

volumes:
  grafana-data:
  loki-data:
  tempo-data:
  promtail-positions:
