apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: 'trace_id=([a-f0-9]{32})'
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: 'View trace'

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '1m'
        spanEndTimeShift: '1m'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        # 👇 Use job label from promtail + trace_id
        query: '{job="flask-app"} | trace_id="${__span.traceId}"'
      serviceMap:
        datasourceUid: loki
