server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: ""

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask-app
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      # Extract trace_id and span_id from log lines
      - regex:
          expression: 'trace_id=(?P<trace_id>[0-9a-f]{32}) span_id=(?P<span_id>[0-9a-f]{16})'
      - labels:
          trace_id:
          span_id:
